import pandas as pd

Questions={
             0:"¿TIENE CLARO EL OBJETIVO DE SU EMPRESA?",
             1:"NOMBRE DE LA EMPRESA",
             2:"¿TIENE CLARO SUS OBJETIVOS SEMANALES?",
             3:"¿PROGRAMA SECIONES PARA DEFINIR LOS OBJETIVOS?",
             4:"¿MANEJA UN CRONOGRAMA CON LOS HITOS IMPORTANTES?",
             5:"¿SE APEGA A LA PLANEACIÓN DE SUS OBJETIVOS EN TIEMPO Y FORMA?",
             6:"¿ADECUA SUS ESTRATEGIAS PARA CUMPLIR CON LAS EXPECTATIVAS DE SUS CLIENTES?",
             7:"¿CAMBIA DE PLANES SIN AVISAR A SU EQUIPO?",
             8:"¿ACTUA DE MANERA RAPIDA PARA RESOLVER UN PROBLEMA?",
             9:"¿EXPLORA NUEVOS CAMINOS PARA RESOLVER UN PROBLEMA?",
             10:"¿SU EQUIPO PROPONE SOLUCIONES PARA RESOLVER UN PROBLEMA?",
             11:"¿PROGRAMA REUNIONES DE TRABAJO CON SU EQUIPO PARA DAR PROPUESTAS?",
             12:"¿ACTUA DE MANERA RAPIDA PARA RESOLVER UN PROBLEMA?",
             13:"¿SOLICITA AYUDA EXTERNA, COMO CONSULTORIAS, PARA RESOLVER UN PROBLEMA?",
             14:"¿TIENE DEFINIDOS CORRECTAMENTE LOS ROLES DENTRO DE SU ORGANIZACIÓN?",
             15:"¿IMPLEMENTA CAPACITACIONES PARA SUS TRABAJADORES?",
             16:"¿IMPLEMENTA KPI PARA TENER ESTATUS DE SUS PROYECTOS?",
             17:"¿INVIERTE EN AUTOMATIZACION DE PROCESOS?",
             18:"¿TIENE UNA PAGINA WEB ?",
             19:"¿TIENE UNA TIENDA ONLINE?",
             20:"¿REALIZA CAMPAÑAS DE MARKETING DIGITAL?",
             21:"¿TIENE SERVICIO DE ATENCION AL CLIENTE?",
             22:"¿DEL TOTAL DE REPORTES QUE MANEJA, QUE PORCENTAJE ESTA AUTOMATIZADO?"
             }

QUESTION_REFERENCE=["¿TIENE CLARO EL OBJETIVO DE SU EMPRESA?",
"¿TIENE CLARO SUS OBJETIVOS SEMANALES?",
"¿PROGRAMA SECIONES PARA DEFINIR LOS OBJETIVOS?",
"¿MANEJA UN CRONOGRAMA CON LOS HITOS IMPORTANTES?",
"¿SE APEGA A LA PLANEACIÓN DE SUS OBJETIVOS EN TIEMPO Y FORMA?",
"¿ADECUA SUS ESTRATEGIAS PARA CUMPLIR CON LAS EXPECTATIVAS DE SUS CLIENTES?",
"¿CAMBIA DE PLANES SIN AVISAR A SU EQUIPO?",
"¿ACTUA DE MANERA RAPIDA PARA RESOLVER UN PROBLEMA?",
"¿EXPLORA NUEVOS CAMINOS PARA RESOLVER UN PROBLEMA?",
"¿SU EQUIPO PROPONE SOLUCIONES PARA RESOLVER UN PROBLEMA?",
"¿PROGRAMA REUNIONES DE TRABAJO CON SU EQUIPO PARA DAR PROPUESTAS?",
"¿ACTUA DE MANERA RAPIDA PARA RESOLVER UN PROBLEMA?",
"¿SOLICITA AYUDA EXTERNA, COMO CONSULTORIAS, PARA RESOLVER UN PROBLEMA?",
"¿TIENE DEFINIDOS CORRECTAMENTE LOS ROLES DENTRO DE SU ORGANIZACIÓN?",
"¿IMPLEMENTA CAPACITACIONES PARA SUS TRABAJADORES?",
"¿IMPLEMENTA KPI PARA TENER ESTATUS DE SUS PROYECTOS?",
"¿INVIERTE EN AUTOMATIZACION DE PROCESOS?",
"¿TIENE UNA PAGINA WEB ?",
"¿TIENE UNA TIENDA ONLINE?",
"¿REALIZA CAMPAÑAS DE MARKETING DIGITAL?",
"¿TIENE SERVICIO DE ATENCION AL CLIENTE?",
"¿DEL TOTAL DE REPORTES QUE MANEJA, QUE PORCENTAJE ESTA AUTOMATIZADO?"]


CATEGORY_REFERENCE=[
"STRATEGY",
"STRATEGY",
"STRATEGY",
"STRATEGY",
"STRATEGY",
"STRATEGY",
"CULTURE",
"CULTURE",
"CULTURE",
"CULTURE",
"CULTURE",
"CULTURE",
"CULTURE",
"ORGANIZATION",
"ORGANIZATION",
"ORGANIZATION",
"ORGANIZATION",
"CAPACITY",
"CAPACITY",
"CAPACITY",
"CAPACITY",
"CAPACITY"]

VALUES_REFERENCE=[10,10,10,10,10,10,10,10,10,10,10,10,10,10,4,1,1,1,1,1,1,10]

def ResumeFormDigitalTransform(data,company):
    """Return a Data Frame resume from the form in the 4 categorys (Strategy,Culture,Organization and Capacity)"""
    
    Only_One_Company=data[data[1]==company]
    Only_One_Company=Only_One_Company.reset_index()
    Only_One_Company.drop(columns=["index"])
    ColumnName=Only_One_Company.iloc[0][1]
    
    Only_One_Company=Only_One_Company.rename(columns=Questions)

    #Transpose the data frame
    Get_Data_Transform=Only_One_Company.transpose()
    Get_Data_Transform=Get_Data_Transform.reset_index()

    #Eliminate the fisrt column
    Get_Data_Transform=Get_Data_Transform.iloc[1:,]
    

    #Rename the dataFrame
    Get_Data_Transform=Get_Data_Transform.rename(columns={0:ColumnName,
                                                      "index":"QUESTIONS"})
    #Eliminate the first column again
    Get_Data_Transform=Get_Data_Transform.iloc[1:,]
    
    #First section
    Get_Data_Transform

    #Get a reference
    DATA_REFERENCE={"REFERENCE":VALUES_REFERENCE,
                    "QUESTIONS":QUESTION_REFERENCE,
                    "CATEGORY":CATEGORY_REFERENCE}

    REFERENCE_DATAFRAME=pd.DataFrame(DATA_REFERENCE)

    #Merge the data
    ALL_DATA=REFERENCE_DATAFRAME.merge(Get_Data_Transform)

    #Create the pivot table
    Operations={'REFERENCE':'sum',ColumnName:'sum'}
    ALL_DATA_GROUP=ALL_DATA.groupby('CATEGORY').agg(Operations)
    ALL_DATA_GROUP['REFERENCE %']=ALL_DATA_GROUP['REFERENCE']/ALL_DATA_GROUP['REFERENCE']
    ALL_DATA_GROUP['REAL %']=ALL_DATA_GROUP[ColumnName]/ALL_DATA_GROUP['REFERENCE']
    ALL_DATA_GROUP=ALL_DATA_GROUP.reset_index()

    return ALL_DATA_GROUP